---
- name: Set proxy for apt
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/80proxy
    owner: root
    group: root
    mode: '0644'
    content: |
      Acquire::http::Proxy "DIRECT";
      Acquire::https::Proxy "DIRECT";

      Acquire::http::Proxy::pkgs.k8s.io "{{ my_proxy.http_proxy }}/";
      Acquire::https::Proxy::pkgs.k8s.io "{{ my_proxy.https_proxy }}/";

      Acquire::http::Proxy::prod-cdn.packages.k8s.io "{{ my_proxy.http_proxy }}/";
      Acquire::https::Proxy::prod-cdn.packages.k8s.io "{{ my_proxy.https_proxy }}/";

      Acquire::http::Proxy::download.docker.com "{{ my_proxy.http_proxy }}/";
      Acquire::https::Proxy::download.docker.com "{{ my_proxy.https_proxy }}/";
  become: true

- name: Create dir for keys
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags:
    - k8s_install
    - k8s_prepare

- name: Install base pkgs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ k8s_base_packages }}"
  tags:
    - k8s_install
    - k8s_prepare

