---
# tasks file for demo.demo.cri-o

- name: Display default value
  ansible.builtin.debug:
    msg: "The value of cri_o_my_variable is {{ cri_o_my_variable }}"

- name: Prepare directories
  ansible.builtin.file:
    dest: "{{item.dest}}"
    state: directory
    owner: root
    group: root
    mode: "{{item.mode | default('0755') }}"
  loop:
   - { dest: /etc/crio/crio.conf.d }
   - { dest: /etc/modules-load.d }
   - { dest: /etc/apt/keyrings }

- name: Configure modules for kernel
  community.general.ini_file:
    path: /etc/modules-load.d/crio.conf
    section: ""
    option: "{{ item.option }}"
    state: "{{ item.state | default('present') }}"
    allow_no_value: true
    mode: "0644"
  loop: "{{ cri_o_modprobe }}"
  notify:
    - cri_o | restart modules

- name: cri_o | activate modprobe
  community.general.modprobe:
    name: "{{ item.option }}"
    state: present
  loop: "{{ cri_o_modprobe }}"
  ignore_errors: "{{ ansible_virtualization_type == 'docker' }}"

- name: Apply systemctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default ('present') }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: true
  loop: "{{ cri_o_sysctl }}"

- name: Trust Kubernetes signing key
  ansible.builtin.shell:
    cmd: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ cri_o_version }}/deb/Release.key -o /etc/apt/keyrings/kubernetes-apt-keyring.asc"
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.asc
  become: true

- name: ADD cri-o repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ cri_o_version }}/deb/ /"
    state: present
    filename: cri-o

- name: Install cri-o package
  ansible.builtin.shell: |
    curl -k -x "{{ my_proxy }}" -L -o /tmp/cri-o.deb "{{ pkg_url }}" && \
    apt-get install -y /tmp/cri-o.deb
  vars:
    my_proxy: "{{ lookup('env', 'https_proxy') | default(lookup('env', 'http_proxy'), true) }}"
    pkg_url: "https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/addons:/cri-o:/stable:/v1.32/deb/amd64/cri-o_1.32.1-1.1_amd64.deb"
  args:
    creates: /tmp/cri-o.deb
  environment:
    https_proxy: "{{ my_proxy }}"
    http_proxy: "{{ my_proxy }}"
  ignore_errors: true

- name: Add logic from  jinja template
  ansible.builtin.template:
    src: etc/crio/crio.conf.d/00-defaults.conf.j2
    dest: /etc/crio/crio.conf.d/00-defaults.conf
    mode: '0644'
  notify:
    - cri_o | restart service

- name: start crio
  ansible.builtin.service:
    name: crio.service
    state: started
    enabled: true
  ignore_errors: true
