---
- name: Prepare system for K8s tests
  hosts: all
  gather_facts: true
  tasks:
    - name: Configure Proxy for APT
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/80proxy
        content: |
          Acquire::http::Proxy "{{ lookup('env', 'http_proxy') }}";
          Acquire::https::Proxy "{{ lookup('env', 'https_proxy') }}";
      when: lookup('env', 'http_proxy') != ""

    - name: Update cache and install base packs
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: true
