apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: myapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}