{{- if .Values.installInfrastructure.traefik }}
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      port: {{ .Values.traefik.ports.web }}
      targetPort: {{ .Values.traefik.ports.web }}
    - name: websecure
      port: {{ .Values.traefik.ports.websecure }}
      targetPort: {{ .Values.traefik.ports.websecure }}
{{- end }}